# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayschedule',
            options={'verbose_name': 'расписание на день', 'verbose_name_plural': 'расписание на день'},
        ),
        migrations.AlterModelOptions(
            name='lectureroom',
            options={'verbose_name': 'аудитория', 'verbose_name_plural': 'аудитории'},
        ),
        migrations.AlterModelOptions(
            name='studygroup',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
        migrations.AlterModelOptions(
            name='studysubject',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='professor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule.Professor'),
            preserve_default=False,
        ),
    ]
