# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20171119_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule.LectureRoom', verbose_name='Аудитория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Professor', verbose_name='Преподаватель'),
        ),
    ]
